### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by charleshansen** [aduth/correctingInterval#3]
Can you `npm publish` the latest version of this? `npm install` gives me version 1.0.4, which does not work in strict mode. Version 2.0 works great when I copy it locally.

**Comment by aduth** [comment]
Hey @charleshansen, thanks for pointing this out. I'll take care of it this evening.

**Comment by aduth** [comment]
`correcting-interval` 2.0.0 published to npm.

https://www.npmjs.com/package/correcting-interval

Thanks again @charleshansen.
